apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/myipaddress

replicas:
  - name: myipaddress
    count: 3

configMapGenerator:
- name: environment
  behavior: merge
  envs:
    - "settings.env"